(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; auto-complete
(depends-on "auto-complete")

;; helm
(depends-on "helm")
(depends-on "helm-swoop") ;; http://fukuyama.co/helm-swoop

;; flycheck
(depends-on "flycheck") ;; http://flycheck.readthedocs.org/en/latest/guide/quickstart.html

;; expand-region
(depends-on "expand-region") ;; https://github.com/magnars/expand-region.el

;; progmodes
(depends-on "markdown-mode") ;; http://jblevins.org/projects/markdown-mode/
